ALTER TABLE application_form_snapshot ADD CONSTRAINT uq_form_snapshot_program_version UNIQUE (source_code, source_program_id, form_version_id);

CREATE TABLE application_form_availability (
 source_code VARCHAR(64) COLLATE utf8mb4_0900_bin NOT NULL,
 source_program_id VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL,
 last_completed_status VARCHAR(32) NULL,
 last_completed_reason_code VARCHAR(200) NULL,
 duration_ms BIGINT NULL,
 timeout_stage VARCHAR(32) NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
 reason_code VARCHAR(200) NOT NULL DEFAULT 'NEW_PROGRAM',
 catalog_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 source_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 parser_version VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NULL,
 extraction_model VARCHAR(200) NULL,
 extraction_prompt_version VARCHAR(71) CHARACTER SET ascii COLLATE ascii_bin NULL,
 active_form_version_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NULL,
 verified_at DATETIME(6) NULL,
 next_retry_at DATETIME(6) NULL,
 attempt_count INT NOT NULL DEFAULT 0,
 generation BIGINT NOT NULL DEFAULT 1,
 lease_token CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 lease_until DATETIME(6) NULL,
 ai_started BOOLEAN NOT NULL DEFAULT FALSE,
 import_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 PRIMARY KEY (source_code, source_program_id),
 CONSTRAINT fk_form_availability_snapshot FOREIGN KEY (source_code, source_program_id, active_form_version_id) REFERENCES application_form_snapshot(source_code, source_program_id, form_version_id),
 CONSTRAINT chk_form_availability_status CHECK (status IN ('PENDING','AVAILABLE','NO_FORM','DOCUMENT_UNAVAILABLE','TOO_LARGE','RETRY_WAITING','STALE','REVIEW_REQUIRED')),
 CONSTRAINT chk_form_availability_active CHECK ((status = 'AVAILABLE' AND active_form_version_id IS NOT NULL AND source_fingerprint IS NOT NULL AND parser_version IS NOT NULL AND extraction_model IS NOT NULL AND extraction_prompt_version IS NOT NULL) OR (status <> 'AVAILABLE' AND active_form_version_id IS NULL)),
 CONSTRAINT chk_form_availability_attempt CHECK (attempt_count >= 0),
 INDEX idx_form_availability_due (next_retry_at, lease_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
