export const applicationPreparationStyles = {
  form: 'flex flex-col gap-5',
  card: 'flex flex-col gap-3 rounded-[1.4rem] border border-sample-border bg-white p-[1.35rem] shadow-[0_8px_24px_rgb(32_33_36_/_4%)]',
  cardTitle: 'm-0 text-[1.02rem] font-bold tracking-[-0.025em] text-app-ink',
  jobList: 'grid gap-3',
  jobItem: 'flex flex-col gap-3 rounded-xl border border-slate-200 bg-slate-50/70 p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between',
  jobTitle: 'block break-words text-sm font-bold leading-6 text-app-ink',
  jobMeta: 'mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs leading-5 text-slate-600',
  jobStatus: 'rounded-full border border-slate-200 bg-white px-2.5 py-0.5 font-semibold text-slate-700',
  muted: 'text-sm leading-6 text-slate-600',
  label: 'text-sm font-bold text-app-ink',
  input: 'block min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus-visible:border-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#087f46] disabled:cursor-not-allowed disabled:bg-slate-100',
  button: 'inline-flex min-h-10 items-center justify-center rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#087f46]',
  primary: 'inline-flex min-h-11 items-center justify-center self-start rounded-full bg-brand-primary px-5 py-2 text-sm font-semibold text-white hover:bg-[#066538] disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#087f46]',
  danger: 'inline-flex min-h-10 items-center justify-center rounded-full border border-red-300 bg-white px-4 py-2 text-sm font-semibold text-red-800 hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-700',
  steps: 'grid grid-cols-2 overflow-hidden rounded-2xl border border-slate-200 bg-white text-sm font-semibold text-slate-500',
  activeStep: 'bg-brand-primary px-4 py-3 text-center text-white',
  inactiveStep: 'px-4 py-3 text-center',
  warning: 'rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950',
  notice: 'rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-700',
  status: 'm-0 text-sm leading-6 text-slate-600',
  list: 'flex flex-col gap-3',
  listLink: 'flex flex-col gap-1 rounded-lg text-app-ink no-underline hover:text-emerald-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#087f46]',
  moreActions: 'flex flex-wrap items-center gap-3',
  officialLink: 'self-start rounded text-sm font-bold text-emerald-800 underline underline-offset-2 hover:text-emerald-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#087f46]',
  details: 'grid gap-2 text-sm [&>div]:grid [&>div]:grid-cols-[minmax(7rem,0.3fr)_1fr] [&>div]:gap-3 [&_dt]:font-bold [&_dt]:text-slate-600 [&_dd]:m-0 [&_dd]:text-app-ink',
  sectionList: 'flex flex-col gap-3',
  sectionItem: 'flex flex-col gap-2 rounded-xl border border-slate-200 p-4',
  sectionHeading: 'flex flex-wrap items-center justify-between gap-2',
  notStarted: 'rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600',
  inProgress: 'rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900',
  confirmed: 'rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-900',
  textarea: 'block min-h-28 w-full resize-y rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm leading-6 focus-visible:border-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#087f46] disabled:cursor-not-allowed disabled:bg-slate-100',
  fieldList: 'grid gap-2 sm:grid-cols-2',
  factItem: 'rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm leading-6',
  suggestion: 'flex flex-col gap-2 rounded-xl border border-sky-200 bg-sky-50 p-3',
  checkboxLabel: 'flex items-start gap-2 text-sm font-bold text-slate-900',
  quote: 'm-0 border-l-2 border-sky-300 pl-3 text-xs leading-5 text-slate-600',
} as const
